'use strict';

const DEFAULT_ACCOUNT_DATA = require('../default_account_data');

describe('default_account_data', function(){
  it('should be as expected', function(){
    expect(DEFAULT_ACCOUNT_DATA).to.deep.equal({
      shared_personal_data: {
        email: true,
        firstname: true,
        lastname: true,
        salutation: true,
        title: true,
        birthdate: true,
        gender: true,
        mailingstreet: true,
        mailingcity: true,
        mailingstate: true,
        mailingpostalcode: true,
        mailingcountry: true,
        homephone: true,
        mobilephone: true,
        faxnumber: true,
        businessname: true,
        businessindustry: true,
        businessstreet: true,
        businesscity: true,
        businesscountry: true,
        businesspostalcode: true,
        businessphone: true,
      },
      personal_data: {
        email: null,
        firstname: null,
        lastname: null,
        salutation: null,
        title: null,
        birthdate: null,
        gender: null,
        mailingstreet: null,
        mailingcity: null,
        mailingstate: null,
        mailingpostalcode: null,
        mailingcountry: null,
        homephone: null,
        mobilephone: null,
        faxnumber: null,
        businessname: null,
        businessindustry: null,
        businessstreet: null,
        businesscity: null,
        businesscountry: null,
        businesspostalcode: null,
        businessphone: null,
      },
      consents: {
        'Brand Marketing': false,
        'Product Marketing': false,
        'New Product Marketing': false,
        'Specific Product Marketing': false,
        'Discount Offers': false,
        'Partner Offers': false,
        'Customer Research': false,
        'Newsletter': false,
        'Membership': false,
        'Volunteering': false,
        'Fundraising': false,
        'Sharing Data within Group': false,
        'Sharing Data with Partners': false,
        'Automated Decision Making': false,
        'Location Tracking': false,
        'Online Tracking': false,
        'Cross-Border Transfers': false,
      },
      communication_channels: {
        email_media: { enabled: false },
        fax_media: { enabled: false },
        postal_mail_media: { enabled: false },
        sms_media: { enabled: false },
        social_media: { enabled: false },
        voice_media: { enabled: false },
      },
    });
  });
});