'use strict';

module.exports = Object.freeze({
  'Brand Marketing': 'The user is granting permission to [Organisation] to send, provide or contact the user with information about their brand, which may include references to products or services. This permission may be revoked at any time at the sole discretion of the user.',
  'Product Marketing': 'The user is granting permission to [Organisation] to send, provide or contact the user with information about their products and services. This permission may be revoked at any time at the sole discretion of the user.',
  'New Product Marketing': ' The user is granting permission to [Organisation] to send, provide or contact the user with information about new or upcoming products or services. This permission may be revoked at any time at the sole discretion of the user.',
  'Specific Product Marketing': 'The user is granting permission to [Organisation] to send, provide or contact the user with information about a specific product or service. This permission is granted on a product-by-product basis and may be revoked in whole or in part at any time at the sole discretion of the user.',
  'Discount Offers': 'The user is granting permission to [Organisation] to send, provide or contact the user with information about discounts or promotions related to the types of goods or services. This permission may be revoked at any time at the sole discretion of the user.',
  'Partner Offers': 'The user is granting permission to [Organisation] to send, provide or contact the user with information about discounts or promotions from their partner organizations. This specifically does not include permission for [Organisation] to share the user\'s personal data with the partner organization. This permission may be revoked at any time at the sole discretion of the user.',
  'Customer Research': 'The user is granting permission to [Organisation] to send, provide, or contact the user with information to enable them to participate in market research including requests for feedback, surveys and other market research. This permission may be revoked at any time at the sole discretion of the user.',
  'Newsletter': 'The user is granting permission to the [Organisation] to send the user a copy or provide them with a link to a periodic newsletter. This permission may be revoked at any time at the sole discretion of the user.',
  'Membership': 'The user is granting permission to [Organisation] to collect or use information about the user and their relationship with [Organisation] to create, maintain, and terminate their participation in a membership rewards program. This permission may be revoked at any time at the sole discretion of the user.',
  'Volunteering': 'The user is granting permission to [Organisation] to collect, use, or disclose information about the user for the purpose of creating, maintaining, or terminating a volunteer relationship with [Organisation]. This permission may be revoked at any time at the sole discretion of the user.',
  'Fundraising': 'The user is granting permission to [Organisation] to send, provide or contact the user with information about current, new or upcoming fundraising programs. This permission may be revoked at any time at the sole discretion of the user.',
  'Sharing Data within Group': 'The user is granting permission to [Organisation] to share information about the user with other areas, business units or parts of their group within [Organisation]. This permission may be revoked at any time at the sole discretion of the user.',
  'Sharing Data with Partners': '[Organisation] may share my data with their 3rd party partners under the same terms',
  'Automated Decision Making': 'The user is granting permission to [Organisation] to process user information for the purpose of automated decision making. This permission may be revoked at any time at the sole discretion of the user.',
  'Location Tracking': 'The user is granting permission to [Organisation] to collect and use location data about the user to provide information or services relevant to the user at particular locations. This data may be retained for location related services. This permission may be revoked at any time at the sole discretion of the user.',
  'Online Tracking': 'The user is granting permission to [Organisation] to collect information about the user using cookies or other technologies for the purpose of providing a customized service to the user. This permission may be revoked at any time at the sole discretion of the user.',
  'Cross-Border Transfers': 'The user is granting permission to [Organisation] to transfer information about the user to other countries for processing or storage, with the proviso that [Organisation] will ensure that overseas processing is also done under these terms. This permission may be revoked at any time at the sole discretion of the user.',
  'Ok to sell my data': 'The user is granting permission to [Organisation] sell the user\’s data for online ads, tracking and marketing, or any other purpose at their sole discretion.',
});
