#!/usr/bin/env bash

set -e
# set -x

PATH=./node_modules/.bin/:$PATH

./scripts/lint

nyc \
  --reporter=html \
  --report-dir=./tmp/coverage \
  --reporter=text \
  mocha $@ $(./scripts/find-specs)

echo "To view the detailed coverage report run:"
echo "(cd ./tmp/coverage && http-server)"
